apiVersion: v1
kind: Pod
metadata:
  name: nodeapp
  labels:
    app: nodeapp
spec:
  containers:
    - name: nodeapp
      image: localhost:32000/nodeapp:tagVersion:registry
      ports:
        - containerPort: 8080
